source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'dotenv-rails'
gem 'slim-rails'
gem 'devise'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'bootstrap-social-rails'
gem 'font-awesome-rails', '4.3.0.0'
gem 'simple_form'
gem 'rails-i18n', '~> 4.0.0'
gem 'seed-fu'
gem 'reform'
gem 'ipaddress'
gem 'nilify_blanks'
gem 'draper'
gem 'gretel'
gem 'pundit'
gem 'beaneater'
gem 'redis-rails'
gem 'friendly_id', '~> 5.1.0'

group :development, :test do
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'factory_girl_rails'
  gem 'quiet_assets'
  gem 'faker'
  gem 'byebug'
end

group :development do
  gem 'letter_opener'
end

